# PostgreSQL RPM Building Project - Yum Repository:
# https://yum.postgresql.org/

- name: Install Postgresql 10 Yum repository
  yum:
    name:
    # - https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7-x86_64/pgdg-centos10-10-2.noarch.rpm
    - https://download.postgresql.org/pub/repos/yum/10/redhat/rhel-7.8-x86_64/pgdg-redhat-repo-42.0-11.noarch.rpm

- name: Install Postgresql 10 packages
  yum:
    name:
    - postgresql10
    - postgresql10-server
    - postgresql10-libs
    - postgresql10-devel
    - postgresql10-odbc
    - postgresql10-plpython

- name: Initialize the database
  command: /usr/pgsql-10/bin/postgresql-10-setup initdb
  args:
    creates: /var/lib/pgsql/10/initdb.log

# A custom file /var/lib/pgsql/10/data/pg_hba.conf is required for the CMR database.
# This file is created by the above "initdb" operation.

- name: Backup of file /var/lib/pgsql/10/data/pg_hba.conf
  command: mv /var/lib/pgsql/10/data/pg_hba.conf /var/lib/pgsql/10/data/pg_hba.conf.orig
  args:
    creates: /var/lib/pgsql/10/data/pg_hba.conf.orig

- name: Create custom /var/lib/pgsql/10/data/pg_hba.conf file
  blockinfile:
    path: /var/lib/pgsql/10/data/pg_hba.conf
    create: yes
    state: present
    owner: postgres
    group: postgres
    mode: 0600
    block: |
      # TYPE	DATABASE	USER	ADDRESS		METHOD
      # "local" is for Unix domain socket connections only
      local	all		all			peer
      # IPv4 local connections:
      host	all		all	127.0.0.1/32	password
      # IPv6 local connections:
      host	all		all	::1/128		password

- name: Start the postgresql-10.service 
  service:
    name=postgresql-10
    state=restarted
    enabled=yes
