- name: "Editing the {{ sendmail_mc }} file to add SMTP relay {{ smtp_relay }}"
  blockinfile:
    path: "{{ sendmail_mc }}"
    state: present
    insertafter: '^dnl define\(`SMART_HOST'', `smtp.your.provider''\)dnl'
    marker: "dnl # {mark} ANSIBLE MANAGED BLOCK"
    block: |
      define(`SMART_HOST', `{{ smtp_relay }}')dnl
      dnl # Relay also unqualified addresses /OHN
      define(`LOCAL_RELAY', `{{ smtp_relay }}')dnl
  notify:
   - Restart Sendmail

- name: Restart and enable the Sendmail service 
  service:
    name=sendmail
    state=restarted
    enabled=yes

- name: Create a cron job for daily restart of sendmail
  cron:
    name: "Sendmail_restart"
    hour: "8"
    minute: "0"
    job: "systemctl restart sendmail"

