- name: Install SNMP packages
  yum:
    name:
    - net-snmp
    - net-snmp-utils

# Enable SNMP monitoring

- name: Removing default syslocation,syscontact in the {{ snmpd_conf }} file
  command: "sed -i.BAK -e '/^syslocation Unknown/d' -e '/^syscontact Root/d' /etc/snmp/snmpd.conf"
  args:
    warn: no

- name: Editing the {{ snmpd_conf }} file
  blockinfile:
    path: "{{ snmpd_conf }}"
    state: present
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # Add the cmaX extension from hp-snmp-agents RPM
      dlmod cmaX /usr/lib64/libcmaX64.so
      rwcommunity public 127.0.0.1
      rocommunity public 127.0.0.1
      rocommunity  public 127.0.0.1
      trapcommunity public
      trapsink 130.225.86.89 public
      syscontact {{ contact }}
      syslocation {{ location }}
  register: snmpd_conf_changed
  vars:
    snmpd_conf: /etc/snmp/snmpd.conf
    contact: support@mail.fysik.dtu.dk

- name: Restart the snmpd service after reconfiguration
  service:
    name: snmpd
    state: restarted
    enabled: yes
  when: snmpd_conf_changed.changed

- name: Open firewall port 161-162/udp (SNMP)
  firewalld:
    port: 161-162/udp
    permanent: true
    state: enabled
  register: firewall_changed

# After configuring firewalld, it must be reloaded
- name: Reload firewalld
  command: firewall-cmd --reload
  when: firewall_changed == "true"
