# Install Dell System Update (DSU)
# http://linux.dell.com/repo/hardware/dsu/

- name: Install packages for CentOS 8
  package:
    name:
    - curl

- name: Copy Dell GPG keys
  copy:
    src: "copygpgkeys.sh"
    dest: "/root/copygpgkeys.sh"

- name: Install Dell GPG keys
  # shell: "curl -s https://linux.dell.com/repo/hardware/dsu/copygpgkeys.sh | bash"
  shell: "bash /root/copygpgkeys.sh"

- name: Copy Dell DSU bootstrap.cgi
  copy:
    src: "bootstrap.cgi"
    dest: "/root/bootstrap.cgi"

- name: Install Dell dell-system-update.repo
  # shell: "curl -O https://linux.dell.com/repo/hardware/dsu/bootstrap.cgi && (yes | bash bootstrap.cgi)"
  shell: "(yes | bash /root/bootstrap.cgi)"

- name: Install dell-system-update and racadm packages
  package:
    name:
    - dell-system-update
    - srvadmin-idracadm7

- name: Create soft-link for racadm command
  file:
    src: /opt/dell/srvadmin/bin/idracadm7
    dest: /usr/local/bin/racadm
    owner: root
    group: root
    state: link
