- name: "Add local host aliases to {{ localhostnames }}"
  blockinfile:
    path: "{{ localhostnames }}"
    state: present
    insertafter: EOF
    block: |
      mail.fysik.dtu.dk
      mail5.fysik.dtu.dk
      servauth2.fysik.dtu.dk
      servauth3.fysik.dtu.dk
      servtsm1.fysik.dtu.dk
      servtsm4.fysik.dtu.dk
      intra4.fysik.dtu.dk
      intra5.fysik.dtu.dk
      web4.fysik.dtu.dk
      web5.fysik.dtu.dk
      demon.fysik.dtu.dk
      demon2.fysik.dtu.dk
      que.fysik.dtu.dk
      audhumbla.fysik.dtu.dk
      niflfs1.fysik.dtu.dk
      niflfs2.fysik.dtu.dk
      niflfs3.fysik.dtu.dk
      niflfs4.fysik.dtu.dk
      niflfs5.fysik.dtu.dk
      niflopt1.fysik.dtu.dk
      niflopt2.fysik.dtu.dk
      niflnet1.fysik.dtu.dk
      niflmgt.fysik.dtu.dk
      niflmgt2.fysik.dtu.dk
      surt.fysik.dtu.dk
      thul.fysik.dtu.dk
      fjorm.fysik.dtu.dk
      sylg.fysik.dtu.dk
      slid.fysik.dtu.dk
      svol.fysik.dtu.dk
      muspel.fysik.dtu.dk
      kepler.fysik.dtu.dk
      nifl.fysik.dtu.dk
      camd.dtu.dk
  notify:
   - Restart Sendmail

- name: "Add mail routing to {{ mailertable }}"
  blockinfile:
    path: "{{ mailertable }}"
    state: present
    insertafter: EOF
    block: |
      .nifl.fysik.dtu.dk	local:
      nifl.fysik.dtu.dk		local:
      listserv.fysik.dtu.dk	smtp:[listserv.fysik.dtu.dk] 
      dtu.dk			smtp:[smtp.ait.dtu.dk] 
      fysik.dtu.dk		smtp:[smtp.ait.dtu.dk] 
      mek.dtu.dk		smtp:[smtp.ait.dtu.dk] 
      adm.dtu.dk		smtp:[smtp.ait.dtu.dk] 
      win.dtu.dk		smtp:[smtp.ait.dtu.dk] 
      student.dtu.dk		smtp:[smtp.ait.dtu.dk]
  notify:
   - Restart Sendmail

- name: "Add mail routing to {{ access }}"
  blockinfile:
    path: "{{ access }}"
    state: present
    insertafter: EOF
    block: |
      # Relay Fysik private network IP range
      10.54			RELAY
  notify:
   - Restart Sendmail

- name: "Remove loopback restriction in {{ sendmail_mc }} to enable sendmail service"
  lineinfile:
    path: "{{ sendmail_mc }}"
    regexp: 'Addr=127\.0\.0\.1'
    line: 'dnl #'

- name: "Add SMTP relay {{ smtp_relay }} to {{ sendmail_mc }} and mail relaying"
  blockinfile:
    path: "{{ sendmail_mc }}"
    state: present
    insertafter: '^dnl define\(`SMART_HOST'', `smtp.your.provider''\)dnl'
    marker: "dnl # {mark} ANSIBLE MANAGED BLOCK"
    block: |
      define(`SMART_HOST', `{{ smtp_relay }}')dnl
      dnl # Relay also unqualified addresses
      define(`LOCAL_RELAY', `{{ smtp_relay }}')dnl
      dnl # Relay mails from our domain
      FEATURE(relay_entire_domain)dnl
  notify:
   - Restart Sendmail

- name: Restart and enable the Sendmail service
  service:
    name=sendmail
    state=restarted
    enabled=yes

- name: Create a cron job for daily restart of sendmail
  cron:
    name: "Sendmail_restart"
    minute: "0"
    hour: "8,20"
    job: "systemctl restart sendmail"

