- name: Install DHCPD and UEFI packages on EL7
  yum:
    name:
    - dhcp
    - dhcp-common
    - dhcp-devel
    - dhcp-libs
    - grub2-efi-x64
    state: present
  when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "7"

- name: Install DHCPD and UEFI packages on EL8
  yum:
    name:
    - dhcp-server
    - dhcp-common
    - dhcp-libs
    - grub2-efi-x64
    state: present
  when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "8"

- name: Create /etc/dhcp/dhcpd.conf.d/ directory for client files
  file:
    path: /etc/dhcp/dhcpd.conf.d
    state: directory
    mode: 0750
    owner: root
    group: root

- name: Create /root/dhcp symlink
  file:
    src: /etc/dhcp/dhcpd.conf.d/
    dest: /root/dhcp
    owner: root
    group: root
    state: link

- name: Open firewall for the DHCPD service
  firewalld:
    service: dhcp
    immediate: true
    permanent: true
    state: enabled

- name: Open firewall for DHCPD port 67/tcp
  firewalld:
    port: 67/tcp
    immediate: true
    permanent: true
    state: enabled

# DO NOT start the dhcpd service unless you have tested it!
#- name: Start and enable the DHCPD service 
#  service:
#    name=dhcpd
#    state=started
#    enabled=yes
