- hosts: camd-desktops
  roles:
   - hostname
   - bashrc
   - epel_repo
   - fusion_repo
   - yum_updates
   - yum_packages
   - authorized_keys_command
   - firewalld_whitelist
   - sendmail_client
   - autofs
   - printers_b307
   - firewalld_reload
