# Configure CMR server basic setup

- hosts: CMR
  roles:
   - rhel7
   - bashrc
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - postgresql
   - cmr_user
   - nhc
   - logwatch
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - yum_updates
   - sendmail_client_ait
