- hosts: demons
  vars:
    firewalld_needs_reload: "false"
  roles:
   - rhel7
   - hostname
   - non_graphical
   - authorized_keys_command
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - no_libvirt
   - sshd_config
   - bashrc
   - epel_repo
   - yum_updates
   - yum_packages
   - sendmail_client
   - desktops_autofs
   - sshblack
   - firewalld_whitelist
   - firewalld_brute_force
   - firewalld_ipset
   - firewalld_reload
