# Configure intra5 server

- hosts: intra5
  roles:
   - rhel7
   - bashrc
   - hostname
   - sudoers
   - non_graphical
   - epel_repo
   - server_packages
   - moinmoin
   - authorized_keys_command
   - nhc
   - rasdaemon
   - logwatch
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - yum_updates
   - fysik_alive_check
   - printerstatus
   - sendmail_aliases
   - sendmail_server
   - DNS_slave
   - tftp_server
   - ftp_server
   - dhcp_server
     # - samba_server
     # - samba_nmbd
   - pxeconfigd
   - nfs_server
   - apache_server
   # Not tested on intra5:
   # - intrawiki
   - firewalld_reload
