# Configure mailing list Mailman server

- hosts: listserv
  roles:
   - rhel8
   - rsyslog
   - bashrc
   - hostname
   - non_graphical
   - dnf_updates
   - epel_repo8
   - dnf_packages_minimal
   - server_packages8
   - proliant_centos8
   - snmp
   - nhc
   # - rasdaemon
   - logwatch
   - logrotate
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - firewalld_whitelist
   - sendmail_listserver
   - apache_server
   - listserver
   - firewalld_reload
