# Configure mail5 server

- hosts: mail5
  roles:
   - rhel7
   - bashrc
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - nhc
   - logwatch
   - logrotate
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - yum_updates
   - firewalld_whitelist
   - sendmail_server
   - firewalld_reload
