# Configure mail server

- hosts: mailserver
  roles:
   - rhel7
   - bashrc
   - hostname
   - non_graphical
   - printerstatus
   - epel_repo
   - server_packages
   - fysik_alive_check
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - yum_updates
   - firewalld_whitelist
   - sendmail_aliases
   - sendmail_server
   - firewalld_reload
