# Configure mirror server

- hosts: mirror3
  roles:
   - rhel8
   - role: linux-system-roles.network
   - datadisk
   - logicalvolume
   - rsyslog
   - bashrc
   - hostname
   - sudoers
   - non_graphical
   - dnf_updates
   - epel_repo
   - dnf_packages_minimal
   - server_packages8
   - proliant_centos8
   - snmp
   - nhc
   # - rasdaemon
   - logwatch
   - logrotate
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   # - firewalld_whitelist
   - apache_server
   - sendmail_aliases
   - sendmail_client
   - aggregate6
   - mirror
   - apache_server
   - firewalld_reload

