# Configure Niflheim NFS file server

## - hosts: gunnthra vid niflbu2 niflopt2 niflfs3
- hosts: Niflheim-NFS
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - niflheim_packages
   - authorized_keys_command
   - over_quota
   - ipmi
   - nhc
   - logwatch
   - logrotate
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - bashrc
   # Do not update automatically the file servers: yum_updates
   - sysctl_bignet
   - niflheim_autofs_servers
   - sendmail_client
   # - slurm_basic
   # - modules
   - nfs_server
   - firewalld_whitelist_niflheim
   - firewalld_reload
