# Configure Niflheim Omni-Path (OPA) network management server

- hosts: Niflheim_opanet
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - authorized_keys_command
   - niflheim_autofs_servers
   - niflheim_opa
   - niflheim_opasnmp
   - niflheim_opafm
   - ipmi
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - bashrc
   - yum_updates
   - sysctl_bignet
   - sendmail_aliases
   - sendmail_client
   - firewalld_whitelist_niflheim
   - firewalld_reload
