# Configure Niflheim login node server

- hosts: Niflheim-login
  roles:
   - rhel7
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - niflheim_packages
   - ipmi
   - niflheim_profile
   - nhc
   - logwatch
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - sshd_config
   - bashrc
   - yum_updates
   - niflheim_autofs
   - niflheim_firewalld
   - sendmail_client
   - slurm_basic
   - modules
   - singularity
