# Configure Niflheim NFS file server

- hosts: Niflheim_NFS
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - datadisk
   - xfs_quota
   - epel_repo
   - server_packages
   - niflheim_packages
   - niflheim_autofs_servers
   - authorized_keys_command
   - snmp
   - over_quota
   - ipmi
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - sshd_config
   - flexlm_user
   - sshd_allow_users
   - bashrc
   - sysctl_bignet
   - sendmail_aliases
   - sendmail_client
   # - slurm_basic
   # - modules
   - nfs_server
   - firewalld_whitelist_niflheim
   - firewalld_reload
