# Configure Niflheim login node server

- hosts: surt 
  roles:
   - rhel7
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - yum_packages
   - nhc
   - logwatch
   - proliant_centos
   - limits_conf
   - no_libvirt
   - sshd_config
   - bashrc
   - yum_updates
   - niflheim_autofs
   - sendmail_client
   - slurm_basic
   - modules
