# Configure Niflheim database file server (MySQL)

- hosts: Niflheim_db
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - authorized_keys_command
   - ipmi
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - bashrc
   - niflheim_autofs_servers
   - slurm_basic
   - slurm_tools
   - slurm_db
   - sendmail_aliases
   - sendmail_client
   - firewalld_whitelist_niflheim
   - firewalld_reload
