# Configure Niflheim network file server (DNS, DHCP, PXE)

## - hosts: niflnet1
- hosts: Niflheim-net
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   # - niflheim_packages
   # - over_quota
   - ipmi
   - nhc
   - logwatch
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - DNS_master
   - sshd_config
   - sshd_allow_users
   - bashrc
   - yum_updates
   - sysctl_bignet
   - niflheim_autofs_servers
   - sendmail_client
   - tftp_server
   - dhcp_server
   # - slurm_basic
   # - modules
   - nfs_server
   - firewalld_whitelist_niflheim
   - firewalld_reload
