# Configure Niflheim NFS file server

- hosts: gunnthra 
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - yum_packages
   - nhc
   - logwatch
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - sshd_config
   - bashrc
   - yum_updates
   - niflheim_autofs
   - sendmail_client
   # - slurm_basic
   # - modules
