# Configure Niflheim NFS file server

## - hosts: gunnthra vid hvergelmer niflopt2 niflfs3
- hosts: Niflheim-NFS
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - niflheim_packages
   - ipmi
   - nhc
   - logwatch
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - bashrc
   - yum_updates
   - niflheim_autofs
   - sendmail_client
   # - slurm_basic
   # - modules
   - nfs_server
   - firewalld_reload
