# Configure Niflheim login node server

- hosts: Niflheim_login
  roles:
   - rhel7
   - lvscratch
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - niflheim_packages
   - ipmi
   - niflheim_profile
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   # Limits disabled, different on slid, sylg etc.
   # - limits_conf
   - proliant_centos
   - no_libvirt
   - sshd_config
   - authorized_keys_command
   - bashrc
   - ls_speedup
   - yum_updates
   - niflheim_autofs
   - niflheim_firewalld
   - sendmail_aliases
   - sendmail_client
   - slurm_basic
   - slurm_tools
   - modules
