# Configure Niflheim network file server (DNS, DHCP, PXE)

- hosts: Niflheim_net
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - sudoers
   - non_graphical
   - epel_repo
   - server_packages
   - authorized_keys_command
   # - niflheim_packages
   # - over_quota
   - ipmi
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos
   # - limits_conf
   - no_libvirt
   - DNS_master
   - sshd_config
   - sshd_allow_users
   - bashrc
   - sysctl_bignet
   - niflheim_autofs_servers
   - sendmail_aliases
   - sendmail_client
   - tftp_server
   - ftp_server
   - dhcp_server
   - pxeconfigd
   # - slurm_basic
   # - modules
   - nfs_server
   - niflheim_alive_check
   - firewalld_whitelist_niflheim
   - firewalld_reload
