# Configure Niflheim NFS file server

- hosts: Niflheim_NFS8
  roles:
   - rhel8
   - role: linux-system-roles.network
   - hostname
   - sudoers
   - bashrc
   - non_graphical
   - datadisk
   - xfs_quota
   - epel_repo
   - server_packages8
   - dell-system-update
   - dell-perccli
   - niflheim_autofs_servers
   - authorized_keys_command
   - snmp
   - over_quota
   - ipmi
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos8
   # - limits_conf
   - no_libvirt
   - flexlm_user
   - sshd_config
   - sshd_allow_users
   - sysctl_bignet
   - sendmail_aliases
   - sendmail_client
   - nfs_server8
   # - samba_server
   # - users
   - firewalld_whitelist_niflheim
   - firewalld_reload
