- hosts: NAT-gateways
  vars:
    firewalld_needs_reload: "false"
  roles:
   - rhel7
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - logwatch
   - no_libvirt
   - sshd_config
   - bashrc
   - yum_updates
   - sendmail_client
