# Configure Niflheim NAT gateway server
# Need to do manually with "nmtui":
# - Configure DNS servers (que, intra4)

- hosts: nigw2
  roles:
   - role: linux-system-roles.network
   - rhel7
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - nhc
   - logwatch
   - proliant_centos
   - no_libvirt
   - sshd_config
   - bashrc
   # - yum_updates
   - sendmail_client
   - firewalld_masquerade
   - DNS_slave
   - firewalld_reload
