# Configure Rsnapshot backup server

- hosts: Rsnapshot
  roles:
   - rhel7
   - role: linux-system-roles.network
   - hostname
   - authorized_keys_command
   - non_graphical
   - epel_repo
   - rsnapshot_autofs
   - server_packages
   - rsnapshot
   - ssh_known_hosts
   - ipmi
   - nhc
   - logwatch
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - bashrc
   - yum_updates
   - sendmail_client
