# Configure Rsnapshot backup server

- hosts: Rsnapshot8
  roles:
   - rhel8
   - logicalvolume
   - software_raid
   - bashrc
   - role: linux-system-roles.network
   - hostname
   - authorized_keys_command
   - non_graphical
   - epel_repo
   - server_packages8
   - snmp
   - rsnapshot_autofs
   - rsnapshot
   - ssh_known_hosts
   - ipmi
   - nhc
   - logwatch
   - proliant_centos8
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - bashrc
   - dnf_updates
   - sendmail_aliases
   - sendmail_client
   - firewalld_reload
