# Niflheim Slurm server CentOS 8

- hosts: pascal
  vars:
    rpm_dir: /root/rpmbuild/RPMS/x86_64
    slurm_id: 1002
    slurm_version: 20.02.6-1
    elversion: "el{{ ansible_facts['distribution_major_version']}}"
    slurm_rpm: "{{ slurm_version }}.{{ elversion }}.x86_64.rpm"
    slurm_dir: /etc/slurm
    slurm_logdir: /var/log/slurm
    mysql_root_password: Edderkop
    clustername: niflheim
  roles:
   - rhel8
   # - role: linux-system-roles.network
   - hostname
   - non_graphical
   # - datadisk
   # - xfs_quota
   - epel_repo
   - server_packages8
   # - niflheim_autofs_servers
   # - authorized_keys_command
   # - snmp
   # - over_quota
   # - ipmi
   # - nhc
   # - rasdaemon
   - logwatch
   - logrotate
   # - proliant_centos8
   # - limits_conf
   - no_libvirt
   # - flexlm_user
   - sshd_config
   - sshd_allow_users
   - bashrc
   - slurm_build
   - slurm_basic
   - slurmdb
   # - sysctl_bignet
   - sendmail_aliases
   - sendmail_client
   # - niflheim_autofs_servers
   # - nfs_server8
   # - samba_server
   # - users
   - firewalld_whitelist_niflheim
   - firewalld_reload
