# Configure web5 server

- hosts: web5
  roles:
   - rhel7
   - bashrc
   - hostname
   - non_graphical
   - epel_repo
   - server_packages
   - desktops_autofs
   - authorized_keys_command
   - nhc
   - rasdaemon
   - logwatch
   - logrotate
   - proliant_centos
   - no_libvirt
   - sshd_config
   - sshd_allow_users
   - yum_updates
   - sendmail_aliases
   - sendmail_client
   - ssl_certificate
   - apache_server
   - web_server
   - davmail
   - firewalld_reload
