# CMR database server: Create the "cmr" user
# See https://docs.ansible.com/ansible/2.6/modules/user_module.html

# NOTE: We permit the CMR administrator (JJ) to make SSH logins to this server
# by adding his SSH public key to ~/.ssh/authorized_keys

- name: Add the user 'cmr' 
  user:
    name: cmr
    comment: Computational Materials Repository
