  - name: Install popular packages 
    yum:
      name: 
      - openssl-devel
      - libibverbs-devel
      - libX11-devel
      - libpciaccess-devel
      - libxml2-devel 
      - glibc-static
      - vim-enhanced
      - redhat-lsb-core
      - nano
      - dos2unix
      state: present
  - name: Install popular packages from the EPEL repository
    yum:
      name:
      - Lmod
      - meld
      - git-all
      - bash-completion
      # DO NOT install the libxc package, it causes problems for GPAW (use modules)
      - python34-pip
      - python2-pip
      - python2-keyring
      - grace
      - python34
      - python-pip
      - python34-pip
      - python34-devel
      - python34-tkinter 
      - GitPython
      - pysvn
      - graphviz
      state: present
