  - name: Install required and popular packages 
    yum:
      name: 
      - emacs
      - gsl
      - gsl-devel
      - gcc-c++
      - tar
      - gzip
      - bzip2
      - unzip
      - xz
      - patch
      - python-setuptools
      - xterm
      - xclip
      - traceroute
      - rclone
      - openssl-devel
      - libibverbs-devel
      - libX11-devel
      - libpciaccess-devel
      - libxml2-devel 
      - glibc-static
      - vim-enhanced
      - redhat-lsb-core
      - nano
      - dos2unix
      - harfbuzz-devel
      - libfabric
      state: present
  - name: Install popular packages from the EPEL repository
    yum:
      name:
      - epel-release
      - Lmod
      - meld
      - git-all
      - bash-completion
      # DO NOT install the libxc package, it causes problems for GPAW (use modules)
      - python34-pip
      - python2-pip
      - python2-keyring
      - python-mock
      - grace
      - python34
      - python-pip
      - python34-pip
      - python34-devel
      - python34-tkinter 
      - GitPython
      - pysvn
      - graphviz
      state: present
