#!/bin/sh

# Executing rsnapshot backups
# Usage: rsnapshots [daily|weekly|monthly|hourly] (default: daily)

# We backup these file systems:
FILESYSTEMS=""

# Commands
RSNAPSHOT=/usr/bin/rsnapshot
# RSNAPSHOTARGS="-v"
RSNAPREPORT=/usr/local/bin/rsnapreport.pl
RSNAPCONFIG=/etc/rsnapshot
# Node health check
NHC=/usr/sbin/nhc

# First a health check
$NHC

# Check if rsnapshot is already running
if test -f /var/run/rsnapshot.pid
then
	echo ERROR: Another rsnapshot is already running:
	ls -l /var/run/rsnapshot.pid
	exit 1
fi

if test $# -gt 0
then
	# Perform backup specified by command arguments
	BACKUPNAME=$*
else
	# This scripts gets called daily, and runs only the "daily" task.
	# On certain days, run the monthly and weekly tasks before that.
	case `LANG=C date +%d` in
		01) $0 monthly ;;
	esac
	
	case `LANG=C date +%a` in
		Sun) $0 weekly ;;
	esac
	# Default: daily backup
	BACKUPNAME=daily
fi

echo
$NHC
echo
echo Executing rsnapshot backups: $BACKUPNAME
echo

# Loop over file systems
for i in $FILESYSTEMS
do
	# Configuration file for this backup
	CONF=$RSNAPCONFIG-$i.conf
	if ! test -s $CONF
	then
		echo ERROR: Configuration file $CONF does not exist or is empty
		continue
	fi
	echo "====================================================================="
	echo
	echo Rsnapshot $BACKUPNAME backup of file system $i starting at `date`
	echo
	# NAS box grahams2 needs extra time to wake up, so first change directory to /home/grahams2
	if test "$i" = "grahams2"
	then
		DIR=/home/$i
		echo Change directory to filesystem $DIR
		(cd $DIR; df -Ph .)
	fi

	$RSNAPSHOT $RSNAPSHOTARGS -c $CONF $BACKUPNAME 2>&1 
	# $RSNAPSHOT $RSNAPSHOTARGS -c $CONF $BACKUPNAME 2>&1 | $RSNAPREPORT
	# $RSNAPSHOT -c $CONF $BACKUPNAME 
done

echo Backups ended at `date`

# Display filesystem data
echo
echo "====================================================================="
df -Phx tmpfs

echo
$NHC
