- include_role:
    name: firewalld_config

- name: Get firewalld rules
  command: "firewall-cmd  --permanent --direct --get-all-rules"
  register: rules
  # Ignore the "changed" status
  changed_when: False

- name: firewalld register INPUT_direct rule for port 22
  vars:
    firewalld_needs_reload: "true"
  command: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct 2 -p tcp --dport 22 -m state --state NEW -m recent --set
  when: "'INPUT_direct 2' not in rules.stdout"

- name: firewalld port 22 reject when hitcount exceeds 4 in 30 seconds
  vars:
    firewalld_needs_reload: "true"
  command: firewall-cmd --permanent --direct --add-rule ipv4 filter INPUT_direct 3 -p tcp --dport 22 -m state --state NEW -m recent --update --seconds 30 --hitcount 4 -j REJECT --reject-with tcp-reset
  when: "'INPUT_direct 3' not in rules.stdout"
