- name: Install Slurm RPM building prerequisite packages
  yum:
    name:
     - epel-release
     - man-db
     - man2html
     - rpm-build
     - gcc
     - http-parser-devel
     - json-c-devel
     - openssl
     - openssl-devel
     - libssh2-devel
     - pam-devel
     - numactl
     - numactl-devel
     - hwloc
     - hwloc-devel
     - lua
     - lua-devel
     - readline-devel
     - rrdtool-devel
     - ncurses-devel
     - gtk2-devel
     - libssh2-devel
     - libibmad
     - libibumad
     - perl-Switch
     - perl-ExtUtils-MakeMaker
     - mariadb-server
     - mariadb-devel
    state: present
