- name: Install EL8 workstation package groups
  dnf:
    name:
    - '@Anaconda tools'
    - '@Core'
    - '@Debugging Tools'
    - '@Desktop Debugging and Performance Tools'
    - '@Fonts'
    - '@GNOME Applications'
    # - '@GNOME'
    - '@Server with GUI'
    - '@Graphical Administration Tools'
    - '@Graphics Creation Tools'
      # - '@Input Methods'
    - '@Internet Applications'
    - '@Internet Browser'
    - '@Java Platform'
    - '@Multimedia'
    - '@Network File System Client'
    - '@Office Suite and Productivity'
    - '@Performance Tools'
      # - '@Printing Client'
    - '@Remote Desktop Clients'
    - '@Development Tools'
    - '@Hardware Monitoring Utilities'
    - '@Scientific Support'

    # Explicit packages:
    - gnome-terminal
    - wmctrl
    - bind-utils
    - tree
    - wget
    - gnuplot
    - mlocate
    - man-pages
    - java-1.8.0-openjdk
    - tcsh
    - net-tools
    - chrony
    - pciutils
    - sendmail
    - sendmail-cf
    - ipmitool
    - nm-connection-editor
    - mcelog
    - hplip
    - bash-completion

- name: Enable a Systemd timer for mlocate-updatedb.timer
  systemd:
    name: mlocate-updatedb.timer
    state: started
    enabled: yes

- name: get default runlevel
  command: systemctl get-default
  register: runlevel
  # Ignore the "changed" status
  changed_when: False

- name: Set graphical runlevel
  command: systemctl set-default graphical.target
  when: runlevel.stdout != "graphical.target"

#- name: Set graphic boot as default boot target
#  file:
#    path=/etc/systemd/system/default.target 
#    src=/lib/systemd/system/graphical.target 
#    state=link
