  - name: Editing the /root/.bashrc file
    blockinfile:
      path: /root/.bashrc
      state: present
      insertafter: '^alias mv=''mv -i'''
      marker: "# {mark} ANSIBLE MANAGED BLOCK"
      block: |
        alias L='ls -la'
        alias m=less
        alias h=history
