#!/bin/bash

#
# Check some nodes by pinging each one
#
# Author: Ole Holm Nielsen, E-mail Ole.H.Nielsen@fysik.dtu.dk, September 2002
#

# Exit the script in case of control-C etc.
trap "exit -1" SIGTERM SIGINT SIGQUIT

STOPFILEDIR=/var/lib/alive
if test ! -d $STOPFILEDIR
then
	mkdir -v $STOPFILEDIR
fi

PING="/bin/ping -c 1 -w 3"

for node in surt.fysik.dtu.dk hp5800a hp5412c hp5412d hp5412e hp5412f hp5412g hpups3 hpups6 hpups7 hpups8 hpups9 vid2 hrid2 mell01 mell02 mell03 mell04 volt01 volt02 volt03 volt04 opa-c1 opa-c2 opa-c3
do
	STOPFILE=$STOPFILEDIR/alive.${node}
	if $PING $node 2>&1 > /dev/null
	then
		if [ -f $STOPFILE ]
		then
			echo Host ${node} is up again
			rm -f $STOPFILE
		fi
	else
		if [ ! -f $STOPFILE ]
		then
			echo Cannot ping host ${node} !
			touch $STOPFILE
		fi

	fi
done
