#!/bin/bash

#
# Check all nodes in a Slurm cluster by pinging each one
#
# Author: Ole Holm Nielsen, Ole.H.Nielsen@fysik.dtu.dk
#

# Exit the script in case of control-C etc.
trap "exit -1" SIGTERM SIGINT SIGQUIT

# PING="/bin/ping -c 1 -w 3"
PING="/bin/ping -c 1 -w 10"
SINFO="/usr/bin/sinfo -N -h"
# The Slurm server nodes list: Only dead nodes (-d)
# NODELIST=`$SINFO -o "%N" -d`
NODELIST=`$SINFO -o "%N"`

STOPFILEDIR=/var/lib/alive
if test ! -d $STOPFILEDIR
then
	mkdir -v $STOPFILEDIR
fi

for node in $NODELIST
do
	STOPFILE=$STOPFILEDIR/alive.${node}
	if $PING $node 2>&1 > /dev/null
	then
		if [ -f $STOPFILE ]
		then
			echo Host ${node} is up again
			$SINFO -n $node
			rm -f $STOPFILE
		fi
	else
		if [ ! -f $STOPFILE ]
		then
			echo Cannot ping host ${node} !
			$SINFO -n $node
			touch $STOPFILE
		fi

	fi
done
