# Set up printer status notifications

- name: Copy the alive check scripts from this server
  copy:
    src: "{{ item }}"
    dest: "/usr/local/bin/"
    backup: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - printerstatus.sh
    - printerreport.sh

- cron:
    name: "Monitor all printers status using SNMP"
    minute: "0"
    hour: "12"
    weekday: "1-5"
    job: "/usr/local/bin/printerstatus.sh |& mail -s 'Fysik printers status' adm-ohni@fysik.dtu.dk"

- cron:
    name: "Send printer reports to responsible people"
    minute: "0"
    hour: "11"
    weekday: "1-5"
    job: "/usr/local/bin/printerreport.sh"
