- name: Copy {{ nhc_rpm }} RPM file
  copy:
    src: "{{ nhc_rpm }}"
    dest: "/tmp/{{ nhc_rpm }}"

- name: Install the LBNL Node Health Check (NHC) package
  yum:
    # name: https://github.com/mej/nhc/releases/download/1.4.2/lbnl-nhc-1.4.2-1.el7.noarch.rpm
    name: "/tmp/{{ nhc_rpm }}"
    state: present

- name: Copy master file {{ nhc_conf }} 
  copy:
    src: "{{ nhc_conf }}"
    dest: "{{ nhc_conf }}"
    owner: root
    group: root
    mode: 0644

- name: Create a cron job for NHC
  cron:
    name: "Node_Health_Check"
    minute: "3"
    job: "/usr/sbin/nhc-wrapper -X 1d"

