---

# This role installs and configures the Slurm Database daemon packages

- name: Install Slurm database prerequisite packages
  yum:
    name:
    - mariadb-server
    - mariadb-devel

- name: Start and enable the Mariadb database service
  service:
    name=mariadb
    state=started
    enabled=yes

- name: Copy mysqlbackup script to /root
  copy:
    src: "mysqlbackup"
    dest: /root
    owner: root
    group: root
    mode: 0700

- name: "Install basic Slurm version {{ slurm_version }} packages from local directory"
  yum:
    name: 
    - "{{ rpm_dir }}/slurm-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-devel-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-slurmdbd-{{ slurm_rpm }}"
    state: present

- name: "Copy slurmdbd.conf to {{ slurm_dir }}"
  copy:
    src: "slurmdbd.conf"
    dest: "{{ slurm_dir }}/"
    owner: slurm
    group: slurm
    mode: 0600

- name: "Create {{ slurm_logdir }} logging directory"
  file:
    path: "{{ slurm_logdir }}"
    state: directory
    mode: 0755
    owner: slurm
    group: slurm

- name: "Create {{ slurm_logdir }} logfile"
  file:
    path: "{{ slurm_logdir }}/slurmdbd.log"
    state: touch
    mode: 0600
    owner: slurm
    group: slurm
