---

# This role installs and configures the Munge service

- name: Add the munge group
  group:
    name: munge
    gid: "{{ munge_id }}"

- name: Add the munge user 
  user:
    name: munge
    comment: "MUNGE Uid N Gid Emporium"
    uid: "{{ munge_id }}"
    group: munge
    home: /var/lib/munge
    shell: /sbin/nologin

- name: Install Munge packages from the EPEL repository
  yum:
    name: munge,munge-libs,munge-devel
    state: present

- name: Configure {{ key_dir }} directory
  file:
    path: "{{ key_dir }}"
    owner: munge
    group: munge
    mode: 0700

- name: Configure {{ log_dir }} directory
  file:
    path: "{{ log_dir }}"
    owner: munge
    group: munge
    mode: 0700

- name: Copy secret site munge key file {{ munge_key }} to {{ key_dir }}
  copy:
    src: "{{ munge_key }}"
    dest: "{{ key_dir }}"
    owner: munge
    group: munge
    mode: 0400

- name: Restart the munge service
  service:
    name: munge
    enabled: yes
    state: restarted
