- name: Install popular packages for CAMD
  package:
    name: 
    - thunderbird
    - libxc-devel
    - openblas-devel
    - openmpi-devel
    - fftw-devel
    - blacs-openmpi-devel
    - scalapack-openmpi-devel 
    - vim-enhanced
    - nano
    - okular
    - python-matplotlib
    - ntfs-3g
    - vim-X11
    - emacs
    - xemacs
    - dos2unix
    - PackageKit-gtk3-module
    - mesa-libGLU
    - gnome-shell
    - gnome-tweak-tool
    - screen
    - reptyr
    - rclone
    - filezilla
    - keepassx2
    state: present

- name: Install popular packages from the EPEL repository
  package:
    name:
    - Lmod
    - git-all
    - bash-completion
    - meld
    - xclip
    - htop
    - rclone
    - GitPython
    state: present
