# CPU architecture
cpu_arch: broadwell

# Environment modules for this CPU architecture
module_path: niflopt1:/u/modules/haswell

location: "DK;Lyngby;Niflheim;B309;059;rack 2;24"

# Roles downloaded from https://galaxy.ansible.com/linux-system-roles/network/
# See https://access.redhat.com/articles/3050101 (Red Hat Enterprise Linux (RHEL) System Roles)
network_connections:
  # Subnet 130.225.86.0/23 on adapter eno1
  - name: "eno1"
    type: "ethernet"
    autoconnect: yes
    mac: 94:18:82:76:45:7c
    ip:
      dhcp4: no
      route_metric4: 1
      gateway4: 130.225.86.1
      auto6: no
      address:
        - 130.225.87.148/23
      dns:
        - 130.225.87.145
        - 130.225.87.140
        - 10.2.128.110
      dns_search:
        - fysik.dtu.dk
        - nifl.fysik.dtu.dk
