  - name: Install system packages 
    dnf:
      name: 
      - libsemanage-python
      - libselinux-python
      - python2-libselinux
      - autofs
      - cups
      - foomatic
      - hplip
      - sendmail-cf
      - openssl-devel
      - libibverbs-devel
      - libX11-devel
      - dos2unix
      - ntfs-3g
      - reptyr
      - fuse-sshfs
      state: present
  - name: Install popular packages 
    dnf:
      name:
      - Lmod
      - git-all
      - bash-completion
#      - texlive-*
      - vim-X11
      - screen
      - vim-enhanced
      - nano
      - okular
      - python-matplotlib
      - sqlitebrowser
      - htop
      - grace
      - python-pip
      # Niflheim: Use modules in stead of these:
      - vtk-python
      - tkinter
      - lapack-devel
      - openblas-devel
      - GitPython
      - pysvn
      - graphviz
      state: present
