- name: Install CentOS server packages for Apache web server
  yum:
    name:
    - httpd
    - mod_ssl
    - selinux-policy-doc
    - rsync
    # EL7 only:
    # - libselinux-python
    # - libsemanage-python
    # - policycoreutils-python
    state: present

- name: SELinux context /u/mirrors
  command:
    chcon -R -t httpd_sys_content_t /u/mirrors

- name: Copy Apache config file mirror.conf
  copy:
    src: "{{ inventory_hostname }}/mirror.conf"
    dest: /etc/httpd/conf.d/
    owner: root
    group: root
    mode: 0644

- name: Create Apache 01mirror.conf symlink
  file:
    src: mirror.conf
    dest: /etc/httpd/conf.d/01mirror.conf
    owner: root
    group: root
    state: link

- name: Copy mirror crontab scripts
  copy:
    src: "{{ item }}"
    dest: /root/
    owner: root
    group: root
    mode: 0755
  with_items:
    - rsync-centos
    - rsync-almalinux
    - rsync-rockylinux

- name: Create mirror directories
  file:
    path: "/u/mirrors/pub/linux/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - centos
    - almalinux
    - rockylinux

- name: Create a cron job for CentOS mirror
  cron:
    name: "CentOS mirror"
    minute: "15"
    hour: "0-23/2"
    job: "/root/rsync-centos"

- name: Create a cron job for AlmaLinux mirror
  cron:
    name: "AlmaLinux mirror"
    minute: "20"
    hour: "*/3"
    job: "/root/rsync-almalinux"

- name: Create a cron job for RockyLinux mirror
  cron:
    name: "RockyLinux mirror"
    minute: "40"
    hour: "*/3"
    job: "/root/rsync-rockylinux"

- name: Copy the catlogfiles script to /usr/local/bin
  copy:
    src: catlogfiles
    dest: "/usr/local/bin/"
    backup: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

