- name: Install popular packages for CAMD
  yum:
    name: 
    - gnome-tweaks
    - thunderbird
    - python3-devel
    - python3-tkinter
    - openblas-devel
    - openmpi-devel
    - fftw-devel
    - blacs-openmpi-devel
    - scalapack-openmpi-devel 
    - vim-enhanced
    - nano
    - ntfs-3g
    - vim-X11
    - emacs
    - PackageKit-gtk3-module
    - mesa-libGLU
    - gnome-shell
    - gnome-tweak-tool
    - screen
    - reptyr
    - rclone
    state: present

- name: Install popular packages from the EPEL repository
  yum:
    name:
    - Lmod
    - git-all
    - bash-completion
    - htop
    - rclone
    state: present

- name: Uninstall environment-modules since we use Lmod
  yum:
    name:
    - environment-modules
    state: absent
