- name: Install popular packages for CAMD
  package:
    name: 
    - libxc-devel
    - gnome-tweaks
    - thunderbird
    - python3-devel
    - python3-tkinter
    - python39
    - python39-devel
    - openblas-devel
    - openmpi-devel
    - fftw-devel
    - blacs-openmpi-devel
    - scalapack-openmpi-devel 
    - vim-enhanced
    - nano
    - ntfs-3g
    - vim-X11
    - emacs
    - dos2unix
    - PackageKit-gtk3-module
    - mesa-libGLU
    - gnome-shell
    - gnome-tweak-tool
    - screen
    - ImageMagick
    - sshfs
    - reptyr
    - rclone
    - syncthing
    - qrencode
    # TeX Live system (if needed):
    # - texlive
    # - texlive-dvipng
    state: present

- name: Install popular packages from the EPEL repository
  package:
    name:
    - Lmod
    - git-all
    - bash-completion
    - htop
    - rclone
    state: present

- name: Uninstall environment-modules since we use Lmod
  package:
    name:
    - environment-modules
    state: absent
