  - name: Install popular packages 
    yum:
      name: vim-enhanced
      state: present
  - name: Install popular packages from the EPEL repository
    yum:
      name: Lmod,git-all,python34-pip,python2-pip
      state: present
