  - name: Install popular packages 
    yum:
      name: 
      - vim-enhanced
      - python-matplotlib
      state: present
  - name: Install popular packages from the EPEL repository
    yum:
      name:
      - Lmod
      - git-all
      - python34-pip
      - python2-pip
      - grace
      state: present
