#!/bin/bash

#
# Check some nodes by pinging each one
#
# Author: Ole Holm Nielsen, E-mail Ole.H.Nielsen@fysik.dtu.dk, September 2002
#

# Exit the script in case of control-C etc.
trap "exit -1" SIGTERM SIGINT SIGQUIT

NODES="svol sylg thul surt slid fjorm"
NODES="$NODES s5248a hp5412f hp5412g"
NODES="$NODES mell01 mell02 mell03 mell04 volt01 volt02 volt03 volt04 opa-c1 opa-c2 opa-c3 opa-c9 opa-c10 opa-c12 opa-c13"
NODES="$NODES sw02d sw04d sw05d sw06d sw07d"
NODES="$NODES sw02m sw04m sw05m sw06m sw07m"
NODES="$NODES sw08d sw09d sw10d sw11d sw12d sw13d sw14d sw15d"
NODES="$NODES sw08m sw09m sw10m sw11m sw12m sw13m sw14m sw15m"
NODES="$NODES hpups8 hpups9"
NODES="$NODES niflopt1 niflopt2 niflopa1 niflmgt2 niflfs1 niflfs2 niflfs3 niflfs4 niflfs5 niflfs6 niflfs7 finbul"
NODES="$NODES niflbu1 niflbu2 niflbu3"

STOPFILEDIR=/var/lib/alive
if test ! -d $STOPFILEDIR
then
	mkdir -v $STOPFILEDIR
fi

PING="/bin/ping -c 1 -w 3"

for node in $NODES
do
	STOPFILE=$STOPFILEDIR/alive.${node}
	if $PING $node 2>&1 > /dev/null
	then
		if [ -f $STOPFILE ]
		then
			echo Host ${node} is up again
			rm -f $STOPFILE
		fi
	else
		if [ ! -f $STOPFILE ]
		then
			echo Cannot ping host ${node} !
			touch $STOPFILE
		fi

	fi
done
