---

# This role installs and configures the Slurm packages

# Install Munge before Slurm
- include_role:
    name: munge

- name: Add the slurm group
  group:
    name: slurm
    gid: "{{ slurm_id }}"

- name: Add the slurm user 
  user:
    name: slurm
    comment: "SLURM workload manager"
    uid: "{{ slurm_id }}"
    group: slurm
    home: /var/lib/slurm
    shell: /bin/bash

- name: Install Slurm prerequisite packages
  yum:
    name:
    - openssl
    #- openssl-devel
    #- pam-devel
    - numactl
    #- numactl-devel
    - hwloc
    #- hwloc-devel
    - lua
    #- lua-devel
    #- readline-devel
    #- rrdtool-devel
    #- ncurses-devel
    #- gtk2-devel
    #- libssh2-devel
    #- libibmad
    #- libibumad
    #- perl-Switch
    #- perl-ExtUtils-MakeMaker
    state: present

- name: Install basic Slurm version {{ slurm_version }} packages from local directory
  yum:
    name: 
    - "{{ rpm_dir }}/slurm-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-perlapi-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-contribs-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-devel-{{ slurm_rpm }}"
    disable_gpg_check: yes
    state: present

- name: Create directory {{ slurm_dir }}
  file:
    path: "{{ slurm_dir }}/"
    state: directory
    owner: root
    group: root
    mode: 0755

# Obsolete (we use configless Slurm)
#- name: Copy Slurm .conf files to {{ slurm_dir }}
#  copy:
#    src: "{{ item }}"
#    dest: "{{ slurm_dir }}/"
#    owner: root
#    group: root
#    mode: 0644
#  with_items:
#    - "{{ rpm_dir }}/slurm.conf"
#    - "{{ rpm_dir }}/cgroup.conf"
#    - "{{ rpm_dir }}/gres.conf"
#    - "{{ rpm_dir }}/topology.conf"

- name: Create log directory {{ slurm_logdir }}
  file:
    path: "{{ slurm_logdir }}/"
    state: directory
    owner: slurm
    group: slurm
    mode: 0755
