---

# This role installs and configures the Slurm packages

# Install Munge before Slurm
- include_role:
    name: munge

- name: Add the slurm group
  group:
    name: slurm
    gid: "{{ slurm_id }}"

- name: Add the slurm user 
  user:
    name: slurm
    comment: "SLURM workload manager"
    uid: "{{ slurm_id }}"
    group: slurm
    home: /var/lib/slurm
    shell: /bin/bash

- name: Install Slurm prerequisite packages
  yum:
    name:
    - gcc
    - rpm-build
    - openssl
    - openssl-devel
    - pam-devel
    - numactl
    - numactl-devel
    - hwloc
    - hwloc-devel
    - lua
    - lua-devel
    - readline-devel
    - rrdtool-devel
    - ncurses-devel
    - gtk2-devel
    - man2html
    - libssh2-devel
    - libibmad
    - libibumad
    - perl-Switch
    - perl-ExtUtils-MakeMaker
    state: present

- name: Install basic Slurm version {{ slurm_version }} packages from local directory
  yum:
    name: 
    - "{{ rpm_dir }}/slurm-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-torque-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-libpmi-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-perlapi-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-contribs-{{ slurm_rpm }}"
    - "{{ rpm_dir }}/slurm-devel-{{ slurm_rpm }}"
    state: present

- name: Create directory {{ slurm_dir }}
  file:
    path: "{{ slurm_dir }}/"
    state: directory
    mode: 0755

- name: Copy site {{ rpm_dir }}/slurm.conf to {{ slurm_dir }}
  copy:
    src: "{{ rpm_dir }}/slurm.conf"
    dest: "{{ slurm_dir }}/"
    owner: root
    group: root
    mode: 0644
