# DTU Fysik web-server configuration

- name: Copy Apache .conf files
  copy:
    src: "{{ item }}"
    dest: "/etc/httpd/conf.d/"
    owner: root
    group: root
    mode: u=rw,g=r,o=r
    backup: yes
  with_items:
    - c2db.conf
    - cmr.conf
    - cmrdb.conf
    - databases.conf
    - dccamd.conf
    - dccamp.conf
    - dcwww_fys_dtu_dk.conf
    - ftp_server.conf
    - wiki.conf

- name: Patch Apache userdir.conf
  patch:
    src: userdir.diff
    dest: "/etc/httpd/conf.d/userdir.conf"
    backup: yes

- name: Copy the catlogfiles script to /usr/local/bin
  copy:
    src: catlogfiles
    dest: "/usr/local/bin/"
    backup: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Set SELinux httpd_use_nfs
  seboolean:
    name: httpd_use_nfs
    state: yes
    persistent: yes

- name: Set SELinux httpd_enable_homedirs
  seboolean:
    name: httpd_enable_homedirs
    state: yes
    persistent: yes

- name: Restart and enable the Apache service 
  service:
    name=httpd
    state=restarted
    enabled=yes
