- name: Check for CentOS/RHEL 8
  fail: msg="This only applies to CentOS/RHEL 8"
  when: ansible_os_family|lower != "redhat" or ansible_distribution_major_version|int != 8

- name: "Set timezone to {{ local_timezone }}"
  timezone:
    name: "{{ local_timezone }}"
  notify: Restart crond
