- name: Check for CentOS/RHEL 8
  fail: msg="This only applies to CentOS/RHEL 8"
  when: ((ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "RedHat") and ansible_facts['distribution_major_version'] != "8") 

- name: "Set timezone to {{ local_timezone }}"
  timezone:
    name: "{{ local_timezone }}"
  notify: Restart crond
