# Setup rsnapshot Remote snapshot

- name: Install required packages from EPEL
  yum:
    name:
    - rsync
    - epel-release
    - rsnapshot
    - logrotate
    - bash-completion
    - git-all
    - vim-enhanced

- name: Remove the mlocate database package because we may have too many files
  yum:
    name: mlocate
    state: absent

# The /usr/share/doc/rsnapshot* folder is different for el7 and el8 rpms, so we must query the package:
- name: Find rsnapreport.pl file on remote machine
  shell: "rpm -ql rsnapshot | grep rsnapreport.pl"
  register: rsnapreport
  # Ignore the "changed" status
  changed_when: False
  args:
    warn: false

- name: Copy the rsnapreport.pl script from the rsnapshot RPM
  copy:
    src: "{{ rsnapreport.stdout }}"
    dest: "/usr/local/bin/"
    remote_src: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: "Copy the rsnapshot master configuration files from this server"
  copy:
    src: "{{ item }}"
    dest: "/etc/"
    backup: yes
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - "rsnapshot-master.conf"
    - "rsnapshot-master-weekly.conf"
    - "rsnapshot-120months.conf"
    - "rsnapshot.exclude"

# Example "backups" variable:
# backups:
#   - backupname: localhost
#     dir: [ '/etc', '/root', '/var/log', '/usr/local' ]
#   - backupname: root-server
#     ssh_connection: "root@server:"
#     subdir: roots/
#     dir: [ '/etc', '/root', '/var/log' ]
#   - backupname: modules
#     dir: [ '/home/modules' ]

# Cannot make this work to append variables to the backups dict:
#- name: Detect root-XXX backups and set ssh_connection
#  set_fact:
#    # item: "{{ item|combine({'ssh_connection':item.backupname|regex_replace('^root-(.*)', 'root@\\1:')}, list_merge='append') }}"
#    item: "{{ item|combine({'ssh_connection':item.backupname|regex_replace('^root-(.*)', 'root@\\1:')}, recursive=True) }}"
#  when: item.backupname|regex_search('^root-')
#  loop:
#    "{{ backups }}"

#- name: "Debug backups"
#  debug:
#    var: backups

#- name: Pause until you can verify updates to an application were successful
#  pause:

# The backup items "backups" are defined in the server host_vars/<nodename> files
- name: "Create /etc/rsnapshot-xxx.conf files"
  blockinfile:
    path: "/etc/rsnapshot-{{ item.backupname }}.conf"
    state: present
    create: yes
    insertafter: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.backupname }}"
    block: |
      # Rsnapshot backup of server {{ item.backupname }}
      snapshot_root	{{ snapshot_root }}/{{ item.subdir|default }}{{ item.backupname }}
      include_conf	/etc/{{ item.include_conf|default('rsnapshot-master.conf') }}
  with_items:
    - "{{ backups }}"

# See https://docs.ansible.com/ansible/2.9/user_guide/playbooks_loops.html#with-subelements
- name: "Nested loop over backup servers and directories appending to /etc/rsnapshot-xxx.conf files"
  blockinfile:
    path: "/etc/rsnapshot-{{ item.0.backupname }}.conf"
    state: present
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.0.backupname }} {{ item.1 }}"
    block: |
      backup	{{ item.0.ssh_connection|default }}{{ item.1 }}/	./	+rsync_long_args=--stats
  loop: "{{ backups|subelements('dir') }}"

- name: "Create the rsnapshot top-level directories in {{ snapshot_root }}"
  file:
    path: "{{ snapshot_root }}/{{ item.subdir|default }}{{ item.backupname }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=,o=
  with_items:
    - "{{ backups }}"

- name: Make a list of all backups
  set_fact:
    backuplist: "{{ backuplist|default }} {{ item.backupname }}"
  loop: "{{ backups }}"

- name: "Debug backuplist"
  debug:
    var: backuplist

- name: Copy the rsnapshots script from this server
  copy:
    src: rsnapshots
    dest: "/root/"
    # backup: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

- name: Add backuplist names to the list in the /root/rsnapshots script 
  lineinfile:
    path: /root/rsnapshots
    backrefs: yes
    regexp: '(^FILESYSTEMS=")(.*)"'
    line: 'FILESYSTEMS="{{ backuplist }}"'

    # Tried various other stuff:
    # insertbefore: '^EOF'
    # line: '{{ item.backupname }}'
    # backrefs: yes
    # backup: yes
    # regexp: '(^FILESYSTEMS=")(.*)(?!{{ item.backupname }})"'
    # regexp: '(^FILESYSTEMS=")(.*)"'
    # line: '\1\2 {{ item.backupname }}"'
  # when: 'item.backupname|string not in \2'
  # with_items:
  #   - "{{ backups }}"

# The backup_start variable defines a cron job start hour (default=23)
- cron:
    name: "Make daily crontab job for backups"
    minute: "1"
    hour: "{{ backup_start|default(23) }}"
    job: "/root/rsnapshots"

# Copy the MoinMoin Wiki pages from backup to /var/moin
- cron:
    name: "Copy MoinMoin Wiki data from backup of intra5"
    minute: "0"
    hour: 7
    job: "rsync -aq --delete /u/snapshots/roots/root-intra5/daily.0/var/moin/ /var/moin/"

- name: Create rsnapshot logrotate script
  copy:
    src: logrotate.rsnapshot
    dest: /etc/logrotate.d/rsnapshot
    owner: root
    group: root
    mode: 0644

