# Setup rsnapshot Remote snapshot

- name: Install required packages from EPEL
  yum:
    name:
    - rsync
    - epel-release
    - rsnapshot
    - logrotate
    - bash-completion
    - git-all
    - vim-enhanced

- name: Copy the rsnapshot configuration files from this server
  copy:
    src: "{{ item }}"
    dest: "/etc/"
    backup: yes
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  with_items:
    - rsnapshot.exclude
    - rsnapshot-master.conf
    - rsnapshot-master-weekly.conf
    - rsnapshot-localhost.conf
    - rsnapshot-root-servauth4.conf
    - rsnapshot-root-mirror2.conf
    - rsnapshot-root-web5.conf
    - rsnapshot-root-intra5.conf
    - rsnapshot-root-servnedi.conf
    - rsnapshot-root-servcamd3.conf
    - rsnapshot-root-que.conf
    - rsnapshot-root-slurmdb.conf
    - rsnapshot-root-niflbu1.conf
    - rsnapshot-root-niflbu2.conf
    - rsnapshot-root-niflbu3.conf
    - rsnapshot-root-niflnet1.conf
    - rsnapshot-root-niflfs1.conf
    - rsnapshot-root-niflfs2.conf
    - rsnapshot-root-niflfs3.conf
    - rsnapshot-root-niflfs4.conf
    - rsnapshot-root-niflfs5.conf
    - rsnapshot-root-niflfs6.conf
    - rsnapshot-root-niflfs7.conf
    - rsnapshot-root-niflopt1.conf
    - rsnapshot-root-niflmgt.conf
    - rsnapshot-root-listserv.conf
    - rsnapshot-root-cinfsql.conf
    - rsnapshot-root-servcinf.conf
    - rsnapshot-root-servxp.conf
    - rsnapshot-camd.conf
    - rsnapshot-niflopt1.conf
    - rsnapshot-modules.conf
    - rsnapshot-cinfsql.conf

- name: Create the rsnapshot top-level directories in /u/snapshots/
  file:
    path: "/u/snapshots/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=,o=
  with_items:
    - localhost
    - roots/root-servauth4
    - roots/root-servnedi
    - roots/root-servcamd3
    - roots/root-servcamd4
    - roots/root-intra5
    - roots/root-que
    - roots/root-slurmdb
    - roots/root-niflbu1
    - roots/root-niflbu2
    - roots/root-niflbu3
    - roots/root-niflnet1
    - roots/root-niflfs1
    - roots/root-niflfs2
    - roots/root-niflfs3
    - roots/root-niflfs4
    - roots/root-niflfs5
    - roots/root-niflfs6
    - roots/root-niflfs7
    - roots/root-niflopt1
    - roots/root-niflmgt
    - roots/root-listserv
    - roots/root-cinfsql
    - roots/root-servxp
    - roots/root-mirror2
    - roots/root-web5

- name: Create the rsnapshot top-level directories in /u/snapshots2/
  file:
    path: "/u/snapshots2/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: u=rwx,g=,o=
  with_items:
    - camd
    - servcinf
    - niflopt1
    - modules
    - cinfsql

- name: Copy the rsnapshots script from this server
  copy:
    src: "{{ item }}"
    dest: "/root/"
    backup: yes
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx
  with_items:
    - rsnapshots

- cron:
    name: "Make daily snapshots of roots and NFS server file systems"
    minute: "1"
    hour: "23"
    job: "/root/rsnapshots"

- name: Create rsnapshot logrotate script
  copy:
    src: logrotate.rsnapshot
    dest: /etc/logrotate.d/rsnapshot
    owner: root
    group: root
    mode: 0644

