  - name: Set SSH authorized keys from files on central server
    authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '{{ item }}') }}"
      # key: "{{ item }}"
    with_items:
      - /root/.ssh/id_ecdsa.pub
      - /root/.ssh/id_dsa_servauth2.pub
