# XFS default quotas

- name: "Create XFS default quotas on file systems"
  xfs_quota:
    type: user
    mountpoint: "{{ item.mountpoint }}"
    bsoft: "{{ xfs_bsoft }}"
    bhard: "{{ xfs_bhard }}"
    isoft: "{{ xfs_isoft }}"
    ihard: "{{ xfs_ihard }}"
  with_items: "{{ filesystems }}"
