# Set up autofs

- name: Start and enable the autofs service
  service:
    name=autofs
    state=started
    enabled=yes

- name: Copy the {{ auto_home }} file from this server
  copy:
    src: "{{ auto_home }}"
    dest: "/etc/auto.home"
    backup: yes
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  notify:
   - Restart autofs

- name: Set SELinux context of file /etc/auto.home to that of {{ auto_master }}
  # Use ls -Z auto_master /etc/auto.home, check if they match
  # This changes the target file auto_home:
  command: /usr/bin/chcon --reference={{ auto_master|quote }} /etc/auto.home
  # Ignore the "changed" status
  changed_when: False

- name: Create file {{ home_autofs }} if it does not exist
  # Method: https://stackoverflow.com/questions/28347717/how-to-create-an-empty-file-with-ansible
  copy:
    content: ""
    dest: "{{ home_autofs }}"
    force: no
    owner: root
    group: root
    mode: 0644

- name: Set SELinux context of file {{ home_autofs }} to that of {{ auto_master }}
  command: /usr/bin/chcon --reference={{ auto_master|quote }} {{ home_autofs|quote }}
  # Ignore the "changed" status
  changed_when: False

- name: Editing the {{ home_autofs }} file
  blockinfile:
    path: "{{ home_autofs }}"
    state: present
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      /home /etc/auto.home --timeout=60
  notify:
   - Restart autofs

- name: SELinux seboolean - Allow NFS mounted home directories
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes

- name: Restart the autofs service
  service:
    name=autofs
    state=restarted
    enabled=yes
