# Create data disk XFS file system on a specified LVM volume
# Variables must be defind in the host_vars/ hostname file

- name: Create a new GPT primary partition for LVM
  parted:
    device: "{{ item }}"
    number: "{{ partition }}"
    # REQUIRED: GPT partition (Ansible default=msdos)
    label: gpt
    flags: [ lvm ]
    state: present
  loop: "{{ disks }}"

# Make a list of the physical volumes, appending partition number (convert to string)
- set_fact:
    pvlist: "{{ pvlist|default([]) + [ item + partition|string ] }}"
  loop: "{{ disks }}"

# The lvg seems to require pvs (physical volumes)
# See https://docs.ansible.com/ansible/latest/modules/lvg_module.html
- name: "Create Volume Group {{ volgroup }} on physical volumes {{ pvlist }}"
  lvg:
    vg: "{{ volgroup }}"
    pvs: "{{ pvlist }}"
    state: present

- include_role:
    name: logicalvolume
