- name: Install the EPEL repository for CentOS/RHEL 8
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    disable_gpg_check: yes
    state: present

# Conditionals for OS 'distribution':
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-facts-distribution

- name: Enable the EPEL PowerTools repository for CentOS 8
  shell: "dnf config-manager --set-enabled PowerTools"
  when: ansible_facts['distribution'] == "CentOS" 
  args:
    warn: no

- name: Enable the codeready-builder-for-rhel-8-{{ ansible_architecture }} repository for RHEL 8
  shell: "subscription-manager repos --enable codeready-builder-for-rhel-8-{{ ansible_architecture }}-rpms"
  when: ansible_facts['distribution'] == "RedHat" 
