- name: Distribution
  debug: msg="{{ ansible_distribution }}"

- name: Install the EPEL repository for CentOS 8
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    disable_gpg_check: yes
    state: present

# Conditionals for distribution:
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-facts-distribution

- name: Enable the EPEL PowerTools repository
  shell: "dnf config-manager --set-enabled PowerTools"
  when: ansible_facts['distribution'] == "CentOS" 
  #args:
  #  warn: no

- name: Enable the codeready-builder-for-rhel-8-{{ ansible_architecture }} repository
  shell: "subscription-manager repos --enable codeready-builder-for-rhel-8-{{ ansible_architecture }}-rpms"
  when: ansible_facts['distribution'] == "RedHat" 
  #args:
  #  warn: no
