  - name: Install server packages
    yum:
      name:
      - bind-utils
      - net-tools
      - jwhois
      - ipmiutil
      - OpenIPMI
      - htop
      - python34
      - Lmod
      - git-all
      - python34-pip
      - python2-pip
      - GitPython
      - grace
      - screen
      - tree
      - glibc
      - libgcc
      - libstdc++
      - nss-softokn-freebl
      - libselinux-python
      - libsemanage-python
      - selinux-policy-doc
      state: present

  - name: remove unwanted packages
    yum:
      name:
      - qemu-*
      - blas*
      - openblas*
      - libreoffice*
      - R-core
      - libRmath
      - vtk
      - vtk-qt
      state: absent
