  - name: Install CentOS server packages
    yum:
      name:
      - man-pages
      - bind-utils
      - net-tools
      - telnet
      - traceroute
      - jwhois
      - expect
      - ipmiutil
      - OpenIPMI
      - net-snmp-utils
      - htop
      - nmap
      - python34
      - Lmod
      - git-all
      - python34-pip
      - python2-pip
      - PackageKit-gtk3-module
      - GitPython
      - grace
      - screen
      - tree
      - glibc
      - libgcc
      - libstdc++
      - nss-softokn-freebl
      - libselinux-python
      - libsemanage-python
      - policycoreutils-python
      - selinux-policy-doc
      state: present

  - name: Remove unwanted packages
    yum:
      name:
      - qemu-*
      - blas*
      - openblas*
      - libreoffice*
      - R-core
      - libRmath
      - vtk
      - vtk-qt
      state: absent
