# CPU architecture
cpu_arch: sandybridge

# Environment modules for this CPU architecture
module_path: niflopt1:/u/modules/sandybridge

# SNMP location
location: "DK;Lyngby;Niflheim;B309;059;rack 13;23;4"

# Roles downloaded from https://galaxy.ansible.com/linux-system-roles/network/
# See https://access.redhat.com/articles/3050101 (Red Hat Enterprise Linux (RHEL) System Roles)
network_connections:
  # Subnet 130.225.86.0/23 on adapter enp3s0f0 (MAC b4:99:ba:bd:68:bc)
  - name: "enp3s0f0"
    type: "ethernet"
    autoconnect: yes
    mac: b4:99:ba:bd:68:bc
    ip:
      dhcp4: no
      route_metric4: 1
      gateway4: 130.225.86.1
      auto6: no
      address:
        - 130.225.86.194/23
      dns:
        - 130.225.87.140
        - 130.225.87.145
        - 10.2.128.110
      dns_search:
        - nifl.fysik.dtu.dk
        - fysik.dtu.dk
  # Subnet 10.2.0.0/16 on PCIe dual-port Ethernet adapter ens3f0 (MAC e8:39:35:02:8d:38)
  - name: "ens3f0"
    type: "ethernet"
    autoconnect: yes
    mac: e8:39:35:02:8d:38
    ip:
      dhcp4: no
      route_metric4: 500
      auto6: no
      address:
        - 10.2.128.105/16
