# Niflheim specific auto.home file
auto_home: auto.home
auto_dtu: auto.dtu
etc_auto_home: /etc/{{ auto_home }}
etc_auto_dtu: /etc/{{ auto_dtu }}

auto_master: /etc/auto.master
home_autofs: /etc/auto.master.d/home.autofs

sysconfig: /etc/sysconfig/autofs
