# Setup Docker on CentOS 8
# https://docs.docker.com/engine/install/centos/

- name: Add docker-ce repository
  shell: 
    cmd: dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    warn: no
  changed_when: False

- name: Add the docker UNIX group
  group:
    name: docker

# See also https://docs.docker.com/engine/security/rootless/
- name: Install Docker packages and prerequisites
  yum:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - shadow-utils
    - fuse-overlayfs
    - iptables
    - policycoreutils-python-utils

- name: Start docker service
  service:
    name=docker
    state=started
    enabled=yes

- name: Start containerd service
  service:
    name=containerd
    state=started
    enabled=yes

