- name: "Editing the {{ sendmail_mc }} file setting SMTP relay {{ smtp_relay }}"
  blockinfile:
    path: "{{ sendmail_mc }}"
    state: present
    insertafter: '^dnl define\(`SMART_HOST'', `smtp.your.provider''\)dnl'
    marker: "dnl # {mark} ANSIBLE MANAGED BLOCK"
    block: |
      define(`SMART_HOST', `{{ smtp_relay }}')dnl
      dnl # Relay also unqualified addresses: Not good for AIT server
      dnl define(`LOCAL_RELAY', `{{ smtp_relay }}')dnl
  notify:
   - Restart Sendmail

- name: "Editing the {{ access }} file turning off TLS for SMTP relay {{ smtp_relay }}"
  blockinfile:
    path: "{{ access }}"
    state: present
    insertafter: EOF
    marker: "dnl # {mark} ANSIBLE MANAGED BLOCK"
    block: |
      Try_TLS:{{ smtp_relay}}		NO
  notify:
   - Restart Sendmail

- name: "Add mail routing to {{ mailertable }}"
  blockinfile:
    path: "{{ mailertable }}"
    backup: yes
    state: present
    insertafter: EOF
    block: |
      .nifl.fysik.dtu.dk        smtp:[mail.fysik.dtu.dk]
      nifl.fysik.dtu.dk         smtp:[mail.fysik.dtu.dk]
      mail.fysik.dtu.dk         smtp:[mail.fysik.dtu.dk]
      listserv.fysik.dtu.dk     smtp:[listserv.fysik.dtu.dk]
      listserv01.fysik.dtu.dk   smtp:[listserv01.fysik.dtu.dk]
  notify:
   - Restart Sendmail


- name: Editing the {{ aliases }} file
  blockinfile:
    path: "{{ aliases }}"
    state: present
    insertafter: '^#root:          marc'
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      root: root@mail.fysik.dtu.dk
      cmr: jensj@fysik.dtu.dk
  notify:
   - Rebuild aliases database

- name: Restart and enable the Sendmail service
  service:
    name=sendmail
    state=restarted
    enabled=yes

- name: Create a cron job for daily restart of sendmail
  cron:
    name: "Sendmail_restart"
    hour: "8"
    job: "systemctl restart sendmail"
