# Niflheim autofs setup

- name: Install the autofs package
  yum:
    name: autofs
    state: present

- name: Touch the {{ etc_auto_home }} file
  file:
    path: "{{ etc_auto_home }}"
    state: touch
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  # Ignore the "changed" status
  changed_when: False

- name: Copy generic mount-points to the {{ etc_auto_home }} file
  blockinfile:
    path: "{{ etc_auto_home }}"
    state: present
    insertbefore: BOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK1"
    block: |
      # Niflheim login node /etc/auto.home
      niflheim2		-rsize=8192,wsize=8192,tcp,vers=3	niflfs3:/u/niflheim2
      que		-rsize=8192,wsize=8192,tcp,vers=3	que:/scratch
      camd		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/camd
      niflheim		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/camd
      niflheim7		-rsize=8192,wsize=8192,tcp,vers=3	niflfs7:/u/camd
      nexmap		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/nexmap
      compute		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/compute
      fotonik		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/fotonik
      qwise		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/qwise
      ppfe		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/ppfe
      cat		-rsize=8192,wsize=8192,tcp,vers=3	niflfs1:/u/cat
      cat5		-rsize=8192,wsize=8192,tcp,vers=3	niflfs5:/u/cat
      mek		-rsize=8192,wsize=8192,tcp,vers=3	niflfs4:/u/mek
      nanomade		-rsize=8192,wsize=8192,tcp,vers=3	niflfs2:/u/nanomade
      energy		-rsize=8192,wsize=8192,tcp,vers=3	niflfs2:/u/energy
      energy6		-rsize=8192,wsize=8192,tcp,vers=3	niflfs6:/u/energy
      opt		-rsize=8192,wsize=8192,tcp,vers=3	niflopt1:/u/opt
      modules		-rsize=8192,wsize=8192,tcp,vers=3	niflopt1:/u/modules/$CPU_ARCH
      scratch1		-rsize=8192,wsize=8192,tcp,vers=3	finbul:/u/scratch
      scratch2		-rsize=8192,wsize=8192,tcp,vers=3	vid:/u/scratch2
  notify:
   - Restart autofs

- name: Set CPU_ARCH in the {{ sysconfig }} file
  blockinfile:
    path: "{{ sysconfig }}"
    state: present
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      OPTIONS="-DCPU_ARCH={{ cpu_arch }}"

- name: Copy file {{ etc_auto_dtu }} 
  copy:
    src: "{{ auto_dtu }}"
    dest: "{{ etc_auto_dtu }}"
    force: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Set SELinux context of file {{ etc_auto_home }} to that of {{ auto_master }}
  # Use ls -Z auto_master auto_home, check if they match
  # This changes the target file auto_home:
  command: /usr/bin/chcon --reference={{ auto_master|quote }} {{ etc_auto_home|quote }}
  # Ignore the "changed" status
  changed_when: False

- name: Create file {{ home_autofs }} if it does not exist
  # Method: https://stackoverflow.com/questions/28347717/how-to-create-an-empty-file-with-ansible
  copy:
    content: ""
    dest: "{{ home_autofs }}"
    force: no
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Set SELinux context of file {{ home_autofs }} to that of {{ auto_master }}
  command: /usr/bin/chcon --reference={{ auto_master|quote }} {{ home_autofs|quote }} 
  # Ignore the "changed" status
  changed_when: False

- name: Editing the {{ home_autofs }} file
  blockinfile:
    path: "{{ home_autofs }}"
    state: present
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      /home {{ etc_auto_home }} --timeout=60
      /dtu {{ etc_auto_dtu }} --timeout=60
  notify:
   - Restart autofs

- name: SELinux seboolean - Allow NFS mounted home directories
  seboolean:
    name: use_nfs_home_dirs
    state: yes
    persistent: yes

- name: Restart autofs
  service:
    name=autofs
    state=restarted
    enabled=yes
