  - name: Install BIND DNS packages
    yum:
      name: bind,bind-libs,bind-utils,net-tools,jwhois
      state: present

  - name: Open firewall port 53 UDP for DNS
    firewalld:
      port: 53/udp
      permanent: true
      state: enabled

  - name: Open firewall port 53 TCP for DNS
    firewalld:
      port: 53/tcp
      permanent: true
      state: enabled
