#
# aggregate6 homepage: https://github.com/job/aggregate6
#
- name: Install aggregate6 prerequisites for EL7
  ansible.builtin.package:
    name:
      - gcc
      - python3
      - python3-devel
    state: present
  when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "7"

- name: Install aggregate6 prerequisites for EL8
  ansible.builtin.package:
    name:
      - gcc
      - platform-python-devel
    state: present
  when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "8"

- name: Install aggregate6 Python3 package.
  pip:
    name: aggregate6
    executable: /usr/bin/pip3
