# Enable the SNMP service
- include_role:
    name: snmp

- name: Get system product name
  command: "dmidecode -s system-product-name"
  register: system_product_name
  changed_when: False

# Run these tasks only for HPE Proliant servers
- include_tasks: hpe_mcp.yml
  when: "'ProLiant' in system_product_name.stdout"
