- name: Install EL8 server packages
  package:
    name:
    - autofs
    - nfs-utils
    - sysstat
    - mdadm
    - policycoreutils
    - selinux-policy
    - selinux-policy-targeted
    - setroubleshoot-server
    - policycoreutils-python-utils
    - mokutil
    - chrony
    - sendmail
    - sendmail-cf
    - make
    - wget
    - whois
    - vim
    - man-pages
    - man-db
    - bind-utils
    - net-snmp
    - net-tools
    - ipcalc
    - tcpdump
    - ipmitool
    - telnet
    - ftp
    - traceroute
    - smartmontools
    - mlocate
    - ack
    - logrotate
    - rsyslog
    - tar
    - patch
    - rsnapshot
    - iftop
    - pv
    - lbzip2
    - rdma-core
    # - jwhois
    - expect
    # - ipmiutil
    - OpenIPMI
    - net-snmp-utils
    - htop
    - nmap
    - git-all
    - screen
    - tree
    - glibc
    - gcc
    - libgcc
    - libstdc++
    - nss-softokn-freebl
    - unzip
    - platform-python-devel
    - autoconf
    - automake
    - fuse-devel
    state: present

- name: Enable a Systemd timer for mlocate-updatedb.timer
  systemd:
    name: mlocate-updatedb.timer
    state: started
    enabled: yes

- name: Remove unwanted packages
  package:
    name:
    - sssd-common
    - sssd-client
    - qemu-*
    - postfix
    - blas*
    # - openblas*
    - libreoffice*
    - R-core
    - libRmath
    - vtk
    - vtk-qt
    state: absent
