# Copy our modified sshd_config file
- name: Copy the {{ sshd_config }} file from this server
  copy:
    src: sshd_config
    dest: "{{ sshd_config }}"
    backup: yes
    owner: root
    group: root
    mode: u=rw,g=,o=
  register: sshd_config_changed

- name: Restart sshd
  service:
    name=sshd
    state=restarted
    enabled=yes
  when: sshd_config_changed.changed
