# Ansible Conditionals for OS 'distribution':
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_conditionals.html#ansible-facts-distribution

# CentOS7 / RHEL7

#- name: Install the EPEL repository for CentOS 7
#  yum:
#    name: epel-release
#    state: present
#  when: (ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7")
#  #args:
#  #  warn: no

- name: Install the EPEL repository for RHEL 7
  yum:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    disable_gpg_check: yes
    state: present
    exclude: "slurm*"
  when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "7"

# CentOS8 / RHEL8

- name: Enable the EPEL powertools repository for CentOS/AlmaLinux/RockyLinux 8
  shell: "dnf config-manager --set-enabled powertools"
  # when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "8"
  when: (ansible_distribution == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_distribution == "AlmaLinux" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_distribution == "RockyLinux" and ansible_facts['distribution_major_version'] == "8") 
  args:
    warn: no
  # Ignore the "changed" status
  changed_when: False

  # NOTE: CentOS 8 Stream also needs epel-next-release, but we can't detect Stream
- name: Install the EPEL repository for CentOS/AlmaLinux/RockyLinux 8
  dnf:
    name: epel-release
    state: present
  when: (ansible_distribution == "CentOS" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_distribution == "AlmaLinux" and ansible_facts['distribution_major_version'] == "8") or
        (ansible_distribution == "RockyLinux" and ansible_facts['distribution_major_version'] == "8") 

- name: Disable slurm packages from the EPEL repo
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    create: no
    section: epel
    option: exclude
    no_extra_spaces: yes
    value: "slurm*"
  # when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "8"

# - name: Disable slurm packages from the EPEL repository for EL7 releases
#  yum_repository:
#    name: epel
#    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
#    description: EPEL YUM repo
#    exclude: "slurm*"
#    when: ansible_os_family|lower == "redhat" and ansible_facts['distribution_major_version'] == "7"

- name: Enable the codeready-builder-for-rhel-8-{{ ansible_architecture }} repository for RHEL 8 ONLY
  shell: "subscription-manager repos --enable codeready-builder-for-rhel-8-{{ ansible_architecture }}-rpms"
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
  args:
    warn: no
  # Ignore the "changed" status
  changed_when: False

- name: Install the EPEL repository for RHEL 8
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    disable_gpg_check: yes
    state: present
    exclude: "slurm*"
  when: ansible_facts['distribution'] == "RedHat" and ansible_facts['distribution_major_version'] == "8"
