- name: Add core limits to /etc/security/limits.conf
  blockinfile:
    path: /etc/security/limits.conf
    state: present
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      # Niflheim configurations
      *		hard    core            0
      *		soft    core            0
      # User jensj runs nightly test
      jensj           hard    cpu             240
      # Normal user limits
      *               hard    cpu             20
      *               hard    rss             50000000
      *               hard    data            50000000
      *               soft    stack           40000000
      *               hard    stack           50000000
      *               hard    nproc           250
      modules               soft    stack           unlimited
      modules               hard    stack           unlimited
      modules               hard    cpu             1000
      modules               hard    nproc           1000
      schiotz               hard    nproc           1000
